import {createCipheriv,createDecipheriv,createHash,randomBytes} from "node:crypto";
import {createAdminClient} from "@/lib/supabase/admin";
import {getGitHubUser} from "@/lib/github";
const TOKEN_URL="https://github.com/login/oauth/access_token";
function key(){const s=process.env.TRAZ_INTERNAL_SECRET;if(!s)throw new Error("TRAZ_INTERNAL_SECRET is not configured");return createHash("sha256").update(s).digest();}
function enc(v:string){const iv=randomBytes(12),c=createCipheriv("aes-256-gcm",key(),iv);const d=Buffer.concat([c.update(v,"utf8"),c.final()]);return `v1.${iv.toString("base64url")}.${c.getAuthTag().toString("base64url")}.${d.toString("base64url")}`;}
function dec(v:string){const [ver,iv,tag,data]=v.split(".");if(ver!=="v1")throw new Error("Invalid GitHub token");const d=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));d.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([d.update(Buffer.from(data,"base64url")),d.final()]).toString("utf8");}
function clientId(){const v=process.env.GITHUB_CLIENT_ID;if(!v)throw new Error("GITHUB_CLIENT_ID is not configured");return v;}
function clientSecret(){const v=process.env.GITHUB_CLIENT_SECRET;if(!v)throw new Error("GITHUB_CLIENT_SECRET is not configured");return v;}
export function githubRedirectUri(){return `${process.env.TRAZ_APP_URL||"http://localhost:3000"}/api/connectors/github/callback`;}
export function createGitHubState(){return randomBytes(32).toString("base64url");}
export function getGitHubAuthorizeUrl(state:string){const p=new URLSearchParams({client_id:clientId(),redirect_uri:githubRedirectUri(),state,scope:"read:user user:email repo offline_access"});return `https://github.com/login/oauth/authorize?${p}`;}
export async function exchangeGitHubCode(code:string){const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:clientId(),client_secret:clientSecret(),code,redirect_uri:githubRedirectUri()})});const d=await r.json();if(!r.ok||d.error||!d.access_token)throw new Error(d.error_description||d.error||"GitHub authorization failed");return d;}
export async function saveGitHubConnection(userId:string,d:any){const user=await getGitHubUser(d.access_token);const db=createAdminClient(),now=Date.now();const {error}=await db.from("github_connections").upsert({user_id:userId,github_user_id:user.id,github_login:user.login,github_name:user.name,github_avatar_url:user.avatar_url,access_token_enc:enc(d.access_token),refresh_token_enc:d.refresh_token?enc(d.refresh_token):null,access_token_expires_at:d.expires_in?new Date(now+d.expires_in*1000).toISOString():null,refresh_token_expires_at:d.refresh_token_expires_in?new Date(now+d.refresh_token_expires_in*1000).toISOString():null,scope:d.scope||null,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(error)throw new Error(error.message);return user;}
async function refresh(row:any,userId:string){if(!row.refresh_token_enc)return null;const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Accept":"application/json","Content-Type":"application/json"},body:JSON.stringify({client_id:clientId(),client_secret:clientSecret(),grant_type:"refresh_token",refresh_token:dec(row.refresh_token_enc)})});const d=await r.json();if(!r.ok||d.error||!d.access_token)throw new Error(d.error_description||d.error||"GitHub token refresh failed");const db=createAdminClient(),now=Date.now();await db.from("github_connections").update({access_token_enc:enc(d.access_token),refresh_token_enc:d.refresh_token?enc(d.refresh_token):row.refresh_token_enc,access_token_expires_at:d.expires_in?new Date(now+d.expires_in*1000).toISOString():null,refresh_token_expires_at:d.refresh_token_expires_in?new Date(now+d.refresh_token_expires_in*1000).toISOString():row.refresh_token_expires_at,scope:d.scope||row.scope,updated_at:new Date().toISOString()}).eq("user_id",userId);return d.access_token;}
export async function getGitHubAccessToken(userId:string){const db=createAdminClient(),{data,error}=await db.from("github_connections").select("*").eq("user_id",userId).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error("GitHub is not connected");const exp=data.access_token_expires_at?new Date(data.access_token_expires_at).getTime():0;if(exp&&exp-Date.now()<120000){const t=await refresh(data,userId);if(t)return t;}return dec(data.access_token_enc);}
export async function getGitHubConnection(userId:string){const db=createAdminClient(),{data,error}=await db.from("github_connections").select("github_user_id,github_login,github_name,github_avatar_url,scope,access_token_expires_at").eq("user_id",userId).maybeSingle();if(error)throw new Error(error.message);return data;}
export async function disconnectGitHub(userId:string){const {error}=await createAdminClient().from("github_connections").delete().eq("user_id",userId);if(error)throw new Error(error.message);}
