import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import ReactMarkdown from"react-markdown";
import remarkGfm from"remark-gfm";
import{Archive,ArchiveRestore,Bot,Check,Copy,FileText,ImagePlus,Menu,Mic,MoreHorizontal,Moon,Pencil,Pin,PinOff,Plus,Search,Send,Settings,Sun,Trash2,User,X,Paperclip,Palette,SlidersHorizontal,Shield,Info,MessageSquare,ChevronRight,Monitor,Clock3}from"lucide-react";
import"./styles.css";

const STORAGE="traz-ai:conversations:v2";
const AUTH="traz-ai:account:v1";
const accountStorage=id=>`traz-ai:conversations:${id}:v1`;
const THEME="traz-ai:theme:v1";
const PREFS="traz-ai:preferences:v1";
const GOOGLE_CLIENT_ID="795721655973-hsimqhadimn2c2htq4u6ifumis9dhequ.apps.googleusercontent.com";
const id=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2)+Date.now();
const fresh=()=>({id:id(),title:"Nova conversa",createdAt:Date.now(),updatedAt:Date.now(),messages:[],pinned:false,archived:false});
function read(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||"[]");return Array.isArray(x)&&x.length?x:[fresh()]}catch{return[fresh()]}}
function readTheme(){try{return localStorage.getItem(THEME)||"system"}catch{return"system"}}
function readAuth(){try{return JSON.parse(localStorage.getItem(AUTH)||"null")}catch{return null}}
function decodeGoogleCredential(credential){try{const part=credential.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");return JSON.parse(decodeURIComponent(atob(part).split("").map(ch=>"%"+("00"+ch.charCodeAt(0).toString(16)).slice(-2)).join("")))}catch{return null}}
function readAccountConversations(account){if(!account?.sub)return[fresh()];try{const x=JSON.parse(localStorage.getItem(accountStorage(account.sub))||"[]");return Array.isArray(x)&&x.length?x:[fresh()]}catch{return[fresh()]}}
function readPrefs(){try{return JSON.parse(localStorage.getItem(PREFS)||"{}")}catch{return{}}}

function App(){
 const[auth,setAuth]=useState(readAuth);
 const[convs,setConvs]=useState(()=>readAccountConversations(readAuth()));
 const[active,setActive]=useState(()=>read().find(c=>!c.archived)?.id||read()[0]?.id);
 const[draft,setDraft]=useState("");const[query,setQuery]=useState("");const[loading,setLoading]=useState(false);const[practiceLoading,setPracticeLoading]=useState(false);const[sidebar,setSidebar]=useState(true);const[menu,setMenu]=useState(null);const[recording,setRecording]=useState(false);const[file,setFile]=useState(null);const[theme,setTheme]=useState(readTheme);const[prefs,setPrefs]=useState(readPrefs);const[settings,setSettings]=useState(false);const[settingsSection,setSettingsSection]=useState("appearance");const input=useRef(null);
 const current=useMemo(()=>convs.find(c=>c.id===active)||convs.find(c=>!c.archived)||convs[0],[convs,active]);
 const visible=convs.filter(c=>!c.archived&&c.title.toLowerCase().includes(query.toLowerCase()));const archived=convs.filter(c=>c.archived);
 useEffect(()=>{if(auth?.sub)localStorage.setItem(accountStorage(auth.sub),JSON.stringify(convs))},[convs,auth]);
 useEffect(()=>{localStorage.setItem(THEME,theme);applyTheme(theme)},[theme]);
 useEffect(()=>localStorage.setItem(PREFS,JSON.stringify(prefs)),[prefs]);
 useEffect(()=>{const listener=e=>{if(e.matches&&theme==="system")applyTheme("system")};const media=window.matchMedia?.("(prefers-color-scheme: light)");media?.addEventListener?.("change",listener);return()=>media?.removeEventListener?.("change",listener)},[theme]);
 const login=credential=>{const data=decodeGoogleCredential(credential);if(!data?.sub)return;const account={sub:data.sub,name:data.name||data.given_name||"Usuário",email:data.email||"",picture:data.picture||""};setAuth(account);localStorage.setItem(AUTH,JSON.stringify(account));const loaded=readAccountConversations(account);setConvs(loaded);setActive(loaded.find(c=>!c.archived)?.id||loaded[0]?.id)};
 const logout=()=>{setAuth(null);localStorage.removeItem(AUTH);setConvs([fresh()]);setActive(null);setSettings(false)};
 const update=fn=>setConvs(x=>x.map(c=>c.id===current?.id?fn(c):c));const newChat=()=>{const c=fresh();setConvs(x=>[c,...x]);setActive(c.id);setDraft("");setSettings(false);setMenu(null)};
 const send=async()=>{if(current?.archived||loading)return;const text=draft.trim();if(!text)return;const now=Date.now();const userMessage={id:id(),role:"user",content:text,createdAt:now};const history=[...(current?.messages||[]),userMessage];update(c=>({...c,title:c.messages.length?c.title:text.length>34?text.slice(0,34)+"…":text,updatedAt:now,messages:[...c.messages,userMessage]}));setDraft("");setLoading(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history.map(m=>({role:m.role,content:m.content}))})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Não foi possível obter uma resposta.");const reply={id:id(),role:"assistant",content:data.reply,createdAt:Date.now()};update(c=>({...c,updatedAt:Date.now(),messages:[...c.messages,reply]}))}catch(error){const reply={id:id(),role:"assistant",content:`Não consegui responder agora. ${error?.message||"Tente novamente em instantes."}`,createdAt:Date.now()};update(c=>({...c,updatedAt:Date.now(),messages:[...c.messages,reply]}))}finally{setLoading(false)}};
 const requestPractice=async()=>{if(!current?.messages?.length||loading||practiceLoading)return;setPracticeLoading(true);try{const history=current.messages.map(m=>({role:m.role,content:m.content}));history.push({role:"user",content:'[MODO PRÁTICA] Retorne APENAS JSON válido neste formato: {"type":"quiz","question":"...","options":["A","B","C","D"],"correctIndex":0,"task":"...","language":"text"}. Crie uma atividade para testar o que o usuário acabou de aprender, respeitando exatamente o assunto e nível estudado. Para conteúdos não relacionados a programação, prefira o modo "open": faça uma pergunta e peça ao usuário para escrever a própria resposta, como uma simulação de prova. Isso deve funcionar para matérias escolares, receitas/culinária, procedimentos, idiomas, conceitos e qualquer conteúdo em que uma resposta livre faça sentido. Isso NÃO é limitado a programação: pode ser matemática, história, ciências, idiomas, receitas, culinária, música, geografia, conceitos, procedimentos, conhecimentos gerais ou qualquer outro conteúdo ensinado. Se for programação, language deve ser a linguagem aprendida (ex.: python, javascript, typescript, luau) e task deve dizer o que fazer no código, SEM dicas de implementação nem solução pronta. Se não for programação, language deve ser "text" e task deve ser uma atividade prática relacionada ao assunto, sem transformar isso em código. O quiz deve ser sempre apropriado ao conteúdo estudado.'});const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history})});const data=await response.json();if(!response.ok)throw new Error(data?.error||"Não foi possível gerar a atividade.");let practice;try{practice=JSON.parse(data.reply.replace(/^\`\`\`json\s*/,"").replace(/\s*\`\`\`$/,"").trim())}catch{practice={type:"quiz",question:"Explique o conceito estudado com suas próprias palavras.",options:["Opção A","Opção B","Opção C","Opção D"],task:"Crie uma pequena solução usando o conceito estudado, sem copiar uma solução pronta.",language:"text"}}const reply={id:id(),role:"assistant",content:"Prática criada com base no que você acabou de estudar.",createdAt:Date.now(),isPractice:true,practice};update(c=>({...c,updatedAt:Date.now(),messages:[...c.messages,reply]}))}catch(error){const reply={id:id(),role:"assistant",content:"Não consegui gerar a atividade agora. "+(error?.message||"Tente novamente em instantes."),createdAt:Date.now(),isPractice:true};update(c=>({...c,updatedAt:Date.now(),messages:[...c.messages,reply]}))}finally{setPracticeLoading(false)}}
 const rename=(conversation=current)=>{const title=prompt("Nome da conversa:",conversation?.title);if(title?.trim())setConvs(x=>x.map(c=>c.id===conversation.id?{...c,title:title.trim(),updatedAt:Date.now()}:c));setMenu(null)};
 const togglePin=c=>{setConvs(x=>x.map(v=>v.id===c.id?{...v,pinned:!v.pinned,updatedAt:Date.now()}:v));setMenu(null)};const archive=c=>{setConvs(x=>x.map(v=>v.id===c.id?{...v,archived:true,updatedAt:Date.now()}:v));if(active===c.id){const next=convs.find(v=>v.id!==c.id&&!v.archived);setActive(next?.id)}setMenu(null)};const restore=c=>{setConvs(x=>x.map(v=>v.id===c.id?{...v,archived:false,updatedAt:Date.now()}:v));setMenu(null)};
 const remove=c=>{if(!confirm("Tem certeza que deseja deletar esta conversa? Esta ação não pode ser desfeita."))return;setConvs(x=>{const y=x.filter(v=>v.id!==c.id),z=y.length?y:[fresh()];if(active===c.id)setActive(z.find(v=>!v.archived)?.id||z[0].id);return z});setMenu(null)};
 const removeAll=()=>{if(!confirm("Excluir todas as conversas? Esta ação não pode ser desfeita."))return;const c=fresh();setConvs([c]);setActive(c.id);setSettingsSection("conversations")};
 const attach=e=>{const f=e.target.files?.[0];if(f)setFile(f)};const openConversation=c=>{if(!c.archived){setActive(c.id);setSettings(false);setMenu(null)}};
 return <div className="app" onClick={()=>menu&&setMenu(null)}>
  <aside className={sidebar?"sidebar":"sidebar collapsed"} onClick={e=>e.stopPropagation()}>
   <div className="brand"><div className="brandMark"><Bot size={20}/></div>{sidebar&&<div><strong>Traz AI</strong><span>Assistente de IA</span></div>}</div>
   {sidebar&&<button className="newChat" onClick={newChat}><Plus size={18}/>Nova conversa</button>}
   {sidebar&&<div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar conversas"/></div>}
   {sidebar&&<div className="sectionLabel">CONVERSAS</div>}
   {sidebar&&<div className="conversationList">{visible.sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updatedAt-a.updatedAt).map(c=><Conversation key={c.id} conversation={c} menu={menu} setMenu={setMenu} onOpen={openConversation} onRename={rename} onPin={togglePin} onArchive={archive} onDelete={remove}/>)}</div>}
   {sidebar&&archived.length>0&&<div className="archivedSection"><div className="sectionLabel">ARQUIVADAS</div>{archived.map(c=><Conversation key={c.id} conversation={c} menu={menu} setMenu={setMenu} onOpen={openConversation} onRename={rename} onPin={togglePin} onArchive={restore} onDelete={remove} archived/>)}</div>}
   <div className="sideBottom">{sidebar&&<div className="accountSection"><AccountArea auth={auth} onLogin={login} onLogout={logout}/></div>}{sidebar&&<div className="settingsButtonWrap"><button className="settingsButton" onClick={()=>{setSettings(true);setSettingsSection("appearance")}}><Settings size={18}/>Configurações</button></div>}</div>
  </aside>
  {sidebar&&<div className="sidebarBackdrop" onClick={()=>setSidebar(false)}/>}
  <main className="main" onClick={()=>{setSidebar(false);setMenu(null)}}>
   <header><div className="mobileMenu" onClick={e=>{e.stopPropagation();setSidebar(x=>!x)}}><Menu size={21}/></div><div className="headerTitle"><span>Traz AI</span></div></header>
   {settings?<SettingsPanel theme={theme} setTheme={setTheme} prefs={prefs} setPrefs={setPrefs} section={settingsSection} setSection={setSettingsSection} removeAll={removeAll}/>:<><div className="chat">{current?.archived?<div className="archivedNotice"><Archive size={28}/><h2>Chat arquivado</h2><p>Este chat está arquivado e não pode receber novas mensagens.</p><button onClick={()=>restore(current)}>Desarquivar chat</button></div>:current?.messages.length===0?<div className="welcome"><div className="welcomeIcon"><Bot size={32}/></div><h1>Converse com o Traz AI</h1><p>Faça perguntas, peça ajuda ou converse com o assistente.</p><div className="suggestions"><button onClick={()=>setDraft("Explique como funciona uma ModuleScript no Roblox.")}>Explique um conceito</button><button onClick={()=>setDraft("Me ajude a criar uma função em Luau.")}>Ajude com código</button><button onClick={()=>setDraft("Analise este arquivo para mim.")}>Analise um arquivo</button></div></div>:current.messages.map((m,index)=><Bubble key={m.id} message={m} practiceAvailable={m.role==="assistant"&&!m.isPractice&&current.messages.slice(0,index).some(item=>item.role==="user"&&isLearningContext(item.content))} onPractice={requestPractice} practiceLoading={practiceLoading}/>)}</div>{!current?.archived&&<div className="composerWrap"><div className="composer">{file&&<div className="attachment"><FileText size={15}/><span>{file.name}</span><X size={14} onClick={()=>setFile(null)}/></div>}<textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Mensagem para o Traz AI..." rows="1"/><div className="composerBar"><div className="tools"><button title="Adicionar arquivo" onClick={()=>input.current?.click()}><Paperclip/></button><input ref={input} hidden type="file" onChange={attach}/><button title="Imagem" onClick={()=>input.current?.click()}><ImagePlus/></button><button className={recording?"recording":""} title="Transcrever áudio" onClick={()=>setRecording(x=>!x)}><Mic/></button></div><button className="send" disabled={!draft.trim()||loading} onClick={send}>{loading?<span className="sendLoading">•••</span>:<Send size={18}/>}</button></div></div><small className="disclaimer">Suas conversas são privadas.</small></div>}</>}
  </main>
 </div>
}

function applyTheme(theme){const value=theme==="system"?(window.matchMedia?.("(prefers-color-scheme: light)").matches?"light":"dark"):theme;document.documentElement.dataset.theme=value}
function AccountArea({auth,onLogin,onLogout}){const ref=useRef(null);useEffect(()=>{if(auth||!ref.current)return;const setup=()=>{if(!window.google||!ref.current)return;ref.current.innerHTML="";window.google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:response=>onLogin(response.credential),auto_select:false,color_scheme:"dark"});window.google.accounts.id.renderButton(ref.current,{theme:"outline",size:"large",shape:"rectangular",text:"signin_with",width:245,locale:"pt-BR"});};if(window.google)setup();else{const script=document.createElement("script");script.id="google-gsi";script.src="https://accounts.google.com/gsi/client";script.async=true;script.defer=true;script.onload=setup;document.head.appendChild(script)}},[auth,onLogin]);if(!auth)return <div className="accountArea"><strong className="accountTitle">Conta</strong><div ref={ref} className="googleButton"/><small>Entre com Google para salvar suas conversas.</small></div>;return <div className="accountArea signed"><div className="accountProfile">{auth.picture?<img src={auth.picture} alt=""/>:<div className="accountAvatar">{(auth.name||"U")[0]}</div>}<div><strong>{auth.name}</strong><span>{auth.email}</span></div></div><button onClick={onLogout}>Sair</button></div>}
function Conversation({conversation:c,menu,setMenu,onOpen,onRename,onPin,onArchive,onDelete,archived=false}){const open=menu===c.id;return <div className={"conversationWrap "+(open?"menuOpen":"")}><button className={"conversation "+(c.archived?"isArchived":"")} onClick={()=>onOpen(c)}><FileText size={14}/><span>{c.pinned&&<Pin size={11} className="pinIcon"/>}{c.title}</span><MoreHorizontal size={16} className="more" onClick={e=>{e.stopPropagation();setMenu(open?null:c.id)}}/></button>{open&&<div className="conversationMenu" onClick={e=>e.stopPropagation()}><button onClick={()=>onPin(c)}>{c.pinned?<PinOff size={15}/>:<Pin size={15}/>}Fixar</button><button onClick={()=>onRename(c)}><Pencil size={15}/>Editar nome</button><button onClick={()=>onArchive(c)}>{archived?<ArchiveRestore size={15}/>:<Archive size={15}/>} {archived?"Desarquivar chat":"Arquivar chat"}</button><button className="danger" onClick={()=>onDelete(c)}><Trash2 size={15}/>Deletar</button></div>}</div>}
function isLearningContext(text=""){const value=text.toLowerCase();return /(ensina|ensine|aprender|aprend[ae]|explica|explique|tutorial|aula|curso|estudar|estudo|exercício|exercicio|quiz|conceito|programa|programação|programacao|python|javascript|typescript|luau|roblox|matemática|matematica|história|historia|ciência|ciencia)/i.test(value)}
function MarkdownMessage({content}){return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({children,href})=><a href={href} target="_blank" rel="noreferrer noopener">{children}</a>,pre:({children})=><pre className="codeBlock">{children}</pre>,code:({className,children,...props})=><code className={className||"inlineCode"} {...props}>{children}</code>}}>{content}</ReactMarkdown>}
function isProgrammingLanguage(language=""){return /^(python|javascript|typescript|luau|lua|java|csharp|c\+\+|cpp|c|rust|go|kotlin|swift|php|ruby|dart|gdscript)$/i.test(String(language).trim())}
function isOpenResponsePractice(practice={}){return String(practice.mode||practice.type||"").toLowerCase()==="open"||String(practice.mode||"").toLowerCase()==="answer"}
const COMPLETION_ITEMS={
 python:["def","class","import","from","return","if","elif","else","for","while","in","range","len","print","True","False","None","str","int","float","list","dict"],
 javascript:["const","let","var","function","return","if","else","for","while","of","in","async","await","class","new","import","export","console","Array","Object","Promise"],
 typescript:["const","let","function","return","interface","type","class","extends","implements","async","await","string","number","boolean","unknown","Record","Array"],
 luau:["local","function","return","if","then","elseif","else","end","for","while","do","in","repeat","until","type","export","local","require","game","workspace","script","Vector3","CFrame","Instance","print","pairs","ipairs","table","string","math"]
};
function CodeEditor({language,value,onChange}){const[open,setOpen]=useState(false);const[items,setItems]=useState([]);const[active,setActive]=useState(0);const ref=useRef(null);const words=COMPLETION_ITEMS[String(language||"").toLowerCase()]||[];const updateSuggestions=text=>{const match=text.match(/[A-Za-z_][A-Za-z0-9_]*$/);const token=match?.[0]||"";if(!token||!isProgrammingLanguage(language)){setItems([]);setOpen(false);return}const next=words.filter(word=>word.toLowerCase().startsWith(token.toLowerCase())&&word.toLowerCase()!==token.toLowerCase()).slice(0,7);setItems(next);setActive(0);setOpen(next.length>0)};const choose=word=>{const match=value.match(/[A-Za-z_][A-Za-z0-9_]*$/);const base=match?value.slice(0,-match[0].length):value;onChange(base+word);setItems([]);setOpen(false);requestAnimationFrame(()=>ref.current?.focus())};return <div className="autocompleteEditor"><textarea ref={ref} className="codeEditor" value={value} onChange={e=>{onChange(e.target.value);updateSuggestions(e.target.value)}} onKeyDown={e=>{if(!open)return;if(e.key==="ArrowDown"){e.preventDefault();setActive(i=>Math.min(i+1,items.length-1))}else if(e.key==="ArrowUp"){e.preventDefault();setActive(i=>Math.max(i-1,0))}else if(e.key==="Tab"||e.key==="Enter"){e.preventDefault();if(items[active])choose(items[active])}else if(e.key==="Escape"){setOpen(false)}}} placeholder="Escreva seu código aqui..." spellCheck={false}/>{open&&<div className="completionList">{items.map((item,index)=><button key={item} className={index===active?"active":""} onMouseDown={e=>{e.preventDefault();choose(item)}}>{item}</button>)}</div>}</div>}
function PracticePanel({message,onPractice,practiceLoading}){const[mode,setMode]=useState("quiz");const[answer,setAnswer]=useState("");const[submitted,setSubmitted]=useState(false);const practice=message.practice||{};const options=practice.options||["Opção A","Opção B","Opção C","Opção D"];const canCode=isProgrammingLanguage(practice.language);const openResponse=isOpenResponsePractice(practice);useEffect(()=>{if(!canCode&&mode==="code")setMode("quiz")},[canCode,mode]);return <div className="practicePanel"><div className="practicePanelHeader"><div><strong>Quer praticar mais?</strong><span>Escolha como você quer praticar este conteúdo.</span></div><div className="practiceModes"><button className={mode==="quiz"?"active":""} onClick={()=>{setMode("quiz");setSubmitted(false)}}>{openResponse?"Resposta":"Quiz"}</button>{canCode&&<button className={mode==="code"?"active":""} onClick={()=>{setMode("code");setSubmitted(false)}}>Código</button>}</div></div>{mode==="quiz"?<div className="quizPractice"><p className="practiceQuestion">{practice.question||"Responda uma questão sobre o conteúdo estudado."}</p><div className="practiceChoices">{options.map((option,index)=><label key={index} className={"practiceChoice "+(answer===String(index)?"selected":"")}><input type="radio" name={"quiz-"+message.id} checked={answer===String(index)} onChange={()=>{setAnswer(String(index));setSubmitted(false)}}/><span>{option}</span></label>)}</div><button className="practiceAction" disabled={!answer} onClick={()=>setSubmitted(true)}>Ver resultado</button>{submitted&&<div className="practiceResult">{practice.correctIndex!==undefined?(Number(answer)===Number(practice.correctIndex)?"✓ Acertou!":"✗ Não foi dessa vez. Você pode pedir à Traz AI uma explicação sem revelar a resposta antes de tentar novamente."):"Resposta registrada. Peça à Traz AI para corrigir quando quiser."}</div>}</div>:<div className="codePractice"><div className="codeTask"><strong>Tarefa</strong><MarkdownMessage content={practice.task||"Escreva uma solução usando o conteúdo estudado, sem receber o código pronto."}/></div><div className="codeEditorWrap"><div className="codeEditorTop"><span>{practice.language||"text"}</span><span>Autocompletar ativo · sem solução pronta</span></div><CodeEditor language={practice.language} value={answer} onChange={setAnswer}/></div><button className="practiceAction" disabled={!answer.trim()} onClick={()=>setSubmitted(true)}>Enviar código</button>{submitted&&<div className="practiceResult">Código enviado para a conversa. Você pode pedir à Traz AI para revisar, apontar problemas e explicar conceitos sem entregar a solução automaticamente.</div>}</div>}<button className="newPractice" onClick={onPractice} disabled={practiceLoading}>{practiceLoading?"Gerando nova atividade…":"Gerar outra atividade"}</button></div>}
function Bubble({message,practiceAvailable,onPractice,practiceLoading}){const[copy,setCopy]=useState(false);return <div className={"row "+message.role}><div className="avatar">{message.role==="user"?<User size={17}/>:<Bot size={17}/>}</div><div className="bubble"><div className="bubbleHead">{message.role==="user"?"Você":"Traz AI"}</div><div className="content markdownContent">{message.role==="assistant"?<MarkdownMessage content={message.content}/>:message.content}</div>{message.role==="assistant"&&<button className="copy" onClick={()=>{navigator.clipboard?.writeText(message.content);setCopy(true);setTimeout(()=>setCopy(false),1200)}}>{copy?<Check size={14}/>:<Copy size={14}/>}</button>}{practiceAvailable&&!message.isPractice&&<PracticePanel message={message} onPractice={onPractice} practiceLoading={practiceLoading}/>}</div></div>}

function SettingsPanel({theme,setTheme,prefs,setPrefs,section,setSection,removeAll}){
 const items=[["appearance","Aparência","Personalize a aparência",Palette],["personalization","Personalização","Defina suas preferências",SlidersHorizontal],["conversations","Conversas","Gerencie suas conversas",MessageSquare],["privacy","Privacidade","Controle sua privacidade",Shield],["about","Sobre","Informações sobre o Traz AI",Info]];
 return <div className="settingsLayout"><nav className="settingsNav"><div className="settingsHeading"><Settings size={21}/><div><h1>Configurações</h1><span>Personalize sua experiência</span></div></div>{items.map(([key,title,desc,Icon])=><button key={key} className={section===key?"active":""} onClick={()=>setSection(key)}><Icon size={18}/><div><strong>{title}</strong><small>{desc}</small></div><ChevronRight size={16}/></button>)}</nav><section className="settingsContent"><SettingsSectionHeader section={section}/>{section==="appearance"&&<Appearance theme={theme} setTheme={setTheme}/>} {section==="personalization"&&<Personalization prefs={prefs} setPrefs={setPrefs}/>} {section==="conversations"&&<ConversationsSettings removeAll={removeAll}/>} {section==="privacy"&&<Privacy/>}{section==="about"&&<About/>}</section></div>
}
function SettingsSectionHeader({section}){const titles={appearance:["Aparência","Escolha como o Traz AI aparece para você."],personalization:["Personalização","Ajuste sua experiência de conversa."],conversations:["Conversas","Gerencie suas conversas e seu histórico."],privacy:["Privacidade","Suas conversas e preferências ficam sob seu controle."],about:["Sobre","Saiba mais sobre o Traz AI."]};return <div className="settingsSectionHeader"><h2>{titles[section][0]}</h2><p>{titles[section][1]}</p></div>}
function Appearance({theme,setTheme}){return <div className="optionCard"><div className="settingRow"><div><strong>Tema</strong><small>Escolha a aparência do aplicativo.</small></div><div className="themeOptions"><button className={theme==="system"?"selected":""} onClick={()=>setTheme("system")}><Monitor size={16}/>Sistema</button><button className={theme==="light"?"selected":""} onClick={()=>setTheme("light")}><Sun size={16}/>Claro</button><button className={theme==="dark"?"selected":""} onClick={()=>setTheme("dark")}><Moon size={16}/>Escuro</button></div></div></div>}
function Personalization({prefs,setPrefs}){return <div className="optionCard"><div className="settingRow column"><div><strong>Instruções personalizadas</strong><small>Conte ao Traz AI como você prefere receber respostas.</small></div><textarea value={prefs.instructions||""} onChange={e=>setPrefs({...prefs,instructions:e.target.value})} placeholder="Ex.: prefiro respostas objetivas e em português." rows="5"/></div></div>}
function ConversationsSettings({removeAll}){return <div className="optionCard"><div className="settingRow"><div><strong>Chats arquivados</strong><small>Você pode acessar seus chats arquivados pela barra lateral.</small></div><Clock3 size={19}/></div><div className="settingRow dangerRow"><div><strong>Excluir todas as conversas</strong><small>Apaga todas as conversas deste dispositivo.</small></div><button onClick={removeAll}>Excluir tudo</button></div></div>}
function Privacy(){return <div className="optionCard"><div className="settingRow"><div><strong>Privacidade</strong><small>Suas preferências ficam sob seu controle.</small></div><Shield size={19}/></div><div className="settingRow"><div><strong>Controle dos seus dados</strong><small>Você pode apagar suas conversas quando quiser usando as opções de conversas.</small></div></div></div>}
function About(){return <div className="optionCard"><div className="settingRow"><div><strong>Traz AI</strong><small>Seu assistente de IA para conversas, ideias e ajuda.</small></div><Bot size={21}/></div><div className="settingRow"><div><strong>Ajuda e feedback</strong><small>Use este espaço para deixar o aplicativo cada vez melhor.</small></div></div></div>}
createRoot(document.getElementById("root")).render(<App/>);